# Generated by Django 4.0.3 on 2022-04-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisement_region_alter_advertisement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
