# Generated by Django 4.0.3 on 2022-04-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_advertisement_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['created_at']},
        ),
    ]
